"""Initial migration.

Revision ID: db5ba55ad8eb
Revises: 
Create Date: 2022-10-27 15:45:55.612227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5ba55ad8eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('iduser')
    )
    op.create_table('student_rating',
    sa.Column('idstudent_rating', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=60), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(length=15), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['user.iduser'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idstudent_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_rating')
    op.drop_table('user')
    # ### end Alembic commands ###
